feat: add product tracking
MoralisWeb3/firebase-extensions pull request #1
Opened 2022-11-01 06:27 UTC by sogunshola

2022-11-01 08:42 UTC, b4rtaz requested changes

2022-11-01 08:42 UTC, b4rtaz commented on streams/functions/src/index.ts
> +Moralis.Core.config.set(CoreConfig.product, 'firebase-auth');
Should be `firebase-streams`.

2022-11-02 09:07 UTC, sogunshola commented on streams/functions/src/index.ts
> +Moralis.Core.config.set(CoreConfig.product, 'firebase-auth');
updated

2022-11-02 09:54 UTC, b4rtaz commented on streams/functions/src/index.ts
> +Moralis.Core.config.set(CoreConfig.product, 'firebase-auth');
Do we have confirmed the product header with the backend team?

2022-11-02 10:13 UTC, sogunshola commented on streams/functions/src/index.ts
> +Moralis.Core.config.set(CoreConfig.product, 'firebase-auth');
Yes I have spoken with the api team and they are adding it to next sprint https://moralisweb3.slack.com/archives/C02J5L3PU4U/p1666702972932029

But I think we can still add the header while we wait for them.

2022-11-02 10:47 UTC, merged